version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "Etc/UTC"
    labels:
      - "🤖 Dependencies"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:15"
      timezone: "Etc/UTC"
    labels:
      - "🤖 Dependencies"
    open-pull-requests-limit: 10
    groups:
      docker-images:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:30"
      timezone: "Etc/UTC"
    labels:
      - "🤖 Dependencies"
    open-pull-requests-limit: 10
    groups:
      python-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"
